[theme]
primaryColor = "#bd0812"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1A1C24"
textColor = "#FAFAFA"
font = "sans serif"
base = "dark"

[server]
enableCORS = true
enableXsrfProtection = true
